--- #YAML:1.0
name: Math-BigInt-Pari
version: 1.11
version_from: lib/Math/BigInt/Pari.pm
license: perl
distribution_type: module
generated_by: Math-BigInt-Pari version 1.11
installdirs: site
requires:
  Math::BigFloat: 1.48
  Math::BigInt: 1.74
  Math::Pari: 2.010602
