# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-BigInt-Pari
version:      1.10
version_from: lib/Math/BigInt/Pari.pm
installdirs:  site
requires:
    Math::BigFloat:                1.42
    Math::BigInt:                  1.68
    Math::Pari:                    2.001804

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
